Feature brenach
SunnySparks/re-former pull request #8
Opened 2021-01-26 23:20 UTC by SunnySparks

This is a reference from https://github.com/SunnySparks/re-former/pull/4

In this pull request we:

Created the HTML form and database models
Created the form_tag and form_for using rails
Enabled edition and created the proper views for said forms

2021-01-27 22:00 UTC, SunnySparks commented
Dear TSE: 
We have been working on trying to solve the Tests/RSpec issue that is displayed since Monday, we are getting lost on this one and we would appreciate if you have any hint or suggestion to find a solution to such issue.

2021-01-27 22:26 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUESTED ♻

### Hey, nice project so far. I noticed that you guys are missing some key features of this project, so we have to improve a few things before moving on:

- [ ] You have linter errors;
- [ ] You have commented code on your users_controller.rb, line 8;
On this project your application should do the following:
- [ ] User can sign in ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_in_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
- [ ] As a signed-in user you can create new post ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/signed_in_can_post_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
- [ ] As a signed-in user you can see post's author ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/signed_in_can_see_author_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
- [ ] User can sign_out ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_out_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
- [ ] As a guest you can see only post's text ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/guest_can_see_only_posts_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))

#### Authentication and User setup

- [ ] The application should use the `devise` gem for authentication ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/bcrypt_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))

- [ ] The application should has Sign in/Sign out links present in any view of the app ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_in_out_link_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49722686/))

- [ ] The User should has*many posts *(not explicity said in specification - [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_associations_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication) but with extra hint - [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/associations_hint_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49722686/) )\_


#### Posts

##### routes

- [ ] The application routes should be created using `resources :posts, only: [:new, :create, :index]` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_routes_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))

##### Post model

- [ ] It should have `belongs_to` a `user` _(not explicity said in specification - [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_associations_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication) but with extra hint - [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/associations_hint_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49722686/) )_

##### PostsController

- [ ] It should use `before_action` to restrict access to the `:new` and `:create` methods (uses ApplicationController helper method) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/before_action_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))

About your question, I wasn't able to find the reason that is causing that error on the rspec.

## As always, I wish you all the very best and see you at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

2021-01-28 17:34 UTC, SunnySparks commented
> # [STATUS] CHANGES REQUESTED ♻
> ### Hey, nice project so far. I noticed that you guys are missing some key features of this project, so we have to improve a few things before moving on:
> * [ ]  You have linter errors;
> * [x]  You have commented code on your users_controller.rb, line 8;
>   On this project your application should do the following:
> * [ ]  User can sign in ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_in_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
> * [ ]  As a signed-in user you can create new post ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/signed_in_can_post_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
> * [ ]  As a signed-in user you can see post's author ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/signed_in_can_see_author_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
> * [ ]  User can sign_out ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_out_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
> * [ ]  As a guest you can see only post's text ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/guest_can_see_only_posts_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
> 
> #### Authentication and User setup
> * [ ]  The application should use the `devise` gem for authentication ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/bcrypt_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
> * [ ]  The application should has Sign in/Sign out links present in any view of the app ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_in_out_link_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49722686/))
> * [ ]  The User should has*many posts *(not explicity said in specification - [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_associations_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication) but with extra hint - [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/associations_hint_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49722686/) )_
> 
> #### Posts
> ##### routes
> * [ ]  The application routes should be created using `resources :posts, only: [:new, :create, :index]` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_routes_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
> 
> ##### Post model
> * [ ]  It should have `belongs_to` a `user` _(not explicity said in specification - [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_associations_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication) but with extra hint - [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/associations_hint_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49722686/) )_
> 
> ##### PostsController
> * [ ]  It should use `before_action` to restrict access to the `:new` and `:create` methods (uses ApplicationController helper method) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/before_action_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
> 
> About your question, I wasn't able to find the reason that is causing that error on the rspec.
> 
> ## As always, I wish you all the very best and see you at the top🚀
> 👨🏻‍💻 **TSE: Kevin Alves**
> 
> 📫 Have any question? Better call Kevin:
> 
> [ ![gmail](https://camo.githubusercontent.com/11be86b5eba8ebd04242b4bc089076ec8b310e961ff2a027b2cf6e92b5f24629/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f676d61696c2d2532302d20677265656e3f6c6f676f3d676d61696c267374796c653d736f6369616c)](mailto:kevinalves.js@gmail.com) [![Twitter Follow](https://camo.githubusercontent.com/cbd0be2e09e3ab22d6166ccd44a79bb6a62f6a854565118238d4ebe5fe2bccf7/68747470733a2f2f696d672e736869656c64732e696f2f747769747465722f666f6c6c6f772f6b6576696e6e6e6d6e3f7374796c653d736f6369616c)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://camo.githubusercontent.com/0fd84d1b61404b93cb8b001ff4bba1bc08cb04f2e7c96fdc94a86a7e0595ab8d/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f536c61636b2d4b6576696e253230416c7665732d677265656e3f6c6f676f3d736c61636b267374796c653d736f6369616c)](https://microverse-students.slack.com/team/UT86D3AP4)

Dear TSE. I'm sorry about the confusion that was generated. As per the changes that are requested, we noticed that such changes belong to a different project, the confusion was generated on **our** end at the time of requesting the code review to a different project that we haven't arrived at yet.
we are kindly requesting a re-revision of our project, and if possible you could provide us some guidance about the Test / RSpec issue our project is facing (As mentioned before, we've been following instructions on the internet such as reinstalling Ruby, erasing the cache, updating the gemfile, etc with no solutions so far. We greatly appreciate your time and feedback.

2021-01-29 00:40 UTC, rindrajosia approved these changes
**status: approved**
Great job @team,  I approve this project but before that, you need to make some changes before merging.

Please  read the comments below.

Happy coding
Rindra Josia.

2021-01-29 00:40 UTC, rindrajosia commented on app/views/users/new.html.erb
>  <%= form_for(@user, url: "/users") do |f| %>
`<%= form_for @user do |f|%>` is enough here.

2021-01-29 00:52 UTC, rindrajosia commented
- [ ] Optional In your form_for, change `<%= f.submit %>` to `<%= f.submit :Submit%>`
- [ ] In your form_tag you don't need this :`<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">`
- [ ] In your form It's preferable to use `users_path` than using `/users`

If you want to run Rspec in your project:

1. Change ruby version in your `Gemfile` and `.ruby-version`
2. add this in you Gemfile:
```
group :development, :test do
  gem 'database_cleaner'
  gem 'capybara'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'launchy'
  gem 'rspec-rails'
end
```
```
group :test do
  gem 'database_cleaner-active_record'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
end
```

3. Use this command to run test: `bundle exec rspec `

2021-01-29 16:49 UTC, SunnySparks commented
> group :test do
>   gem 'database_cleaner-active_record'
>   gem 'selenium-webdriver'
>   # Easy installation and use of chromedriver to run system tests with Chrome
>   gem 'chromedriver-helper'
> end

Thank you for assisting us on the RSpec matter, I really appreciate it. I already made the requested changes as well

2021-01-29 16:55 UTC, merged